config/routes.rb
Rails.application.routes.draw do
  get 'bienvenida/index'
  root 'bienvenida#index'

  resources :actividads
  resources :agencia
  resources :turista
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actividad.rb
class Actividad < ApplicationRecord
end

app/models/agencium.rb
class Agencium < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/turistum.rb
class Turistum < ApplicationRecord
end

app/controllers/actividads_controller.rb
class ActividadsController < ApplicationController
  before_action :set_actividad, only: [:show, :edit, :update, :destroy]

  # GET /actividads
  # GET /actividads.json
  def index
    @actividads = Actividad.all
  end

  # GET /actividads/1
  # GET /actividads/1.json
  def show
  end

  # GET /actividads/new
  def new
    @actividad = Actividad.new
  end

  # GET /actividads/1/edit
  def edit
  end

  # POST /actividads
  # POST /actividads.json
  def create
    @actividad = Actividad.new(actividad_params)

    respond_to do |format|
      if @actividad.save
        format.html { redirect_to @actividad, notice: 'Actividad was successfully created.' }
        format.json { render :show, status: :created, location: @actividad }
      else
        format.html { render :new }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actividads/1
  # PATCH/PUT /actividads/1.json
  def update
    respond_to do |format|
      if @actividad.update(actividad_params)
        format.html { redirect_to @actividad, notice: 'Actividad was successfully updated.' }
        format.json { render :show, status: :ok, location: @actividad }
      else
        format.html { render :edit }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actividads/1
  # DELETE /actividads/1.json
  def destroy
    @actividad.destroy
    respond_to do |format|
      format.html { redirect_to actividads_url, notice: 'Actividad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actividad
      @actividad = Actividad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actividad_params
      params.require(:actividad).permit(:nombre, :lugar, :precio)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bienvenida_controller.rb
class BienvenidaController < ApplicationController
  def index
  end
end

app/helpers/actividads_helper.rb
module ActividadsHelper
end

app/helpers/agencia_helper.rb
module AgenciaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenida_helper.rb
module BienvenidaHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/turista_helper.rb
module TuristaHelper
end

app/views/actividads/_form.html.erb
<%= form_for(actividad) do |f| %>
  <% if actividad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actividad.errors.count, "error") %> prohibited this actividad from being saved:</h2>

      <ul>
      <% actividad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :lugar %>
    <%= f.text_field :lugar %>
  </div>

  <div class="field">
    <%= f.label :precio %>
    <%= f.number_field :precio %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actividads/edit.html.erb
<h1>Editing Actividad</h1>

<%= render 'form', actividad: @actividad %>

<%= link_to 'Show', @actividad %> |
<%= link_to 'Back', actividads_path %>

app/views/actividads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actividads</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Lugar</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actividads.each do |actividad| %>
      <tr>
        <td><%= actividad.nombre %></td>
        <td><%= actividad.lugar %></td>
        <td><%= actividad.precio %></td>
        <td><%= link_to 'Show', actividad %></td>
        <td><%= link_to 'Edit', edit_actividad_path(actividad) %></td>
        <td><%= link_to 'Destroy', actividad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actividad', new_actividad_path %>

app/views/actividads/new.html.erb
<h1>New Actividad</h1>

<%= render 'form', actividad: @actividad %>

<%= link_to 'Back', actividads_path %>

app/views/actividads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @actividad.nombre %>
</p>

<p>
  <strong>Lugar:</strong>
  <%= @actividad.lugar %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @actividad.precio %>
</p>

<%= link_to 'Edit', edit_actividad_path(@actividad) %> |
<%= link_to 'Back', actividads_path %>

app/views/agencia/edit.html.erb
<h1>Editing Agencium</h1>

<%= render 'form', agencium: @agencium %>

<%= link_to 'Show', @agencium %> |
<%= link_to 'Back', agencia_path %>

app/views/agencia/new.html.erb
<h1>New Agencium</h1>

<%= render 'form', agencium: @agencium %>

<%= link_to 'Back', agencia_path %>

app/views/bienvenida/index.html.erb
<h1>'Bienvenido a diskover'</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diskover</title>
    <%= csrf_meta_tags %>


	
  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/turista/edit.html.erb
<h1>Editing Turistum</h1>

<%= render 'form', turistum: @turistum %>

<%= link_to 'Show', @turistum %> |
<%= link_to 'Back', turista_path %>

app/views/turista/new.html.erb
<h1>New Turistum</h1>

<%= render 'form', turistum: @turistum %>

<%= link_to 'Back', turista_path %>